## 소프트맥스 함수 구현

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
a = np.array([0.3, 2.9, 4.0])

exp_a = np.exp(a)

In [4]:
exp_a

array([ 1.34985881, 18.17414537, 54.59815003])

In [5]:
sum_exp_a = np.sum(exp_a)

In [6]:
sum_exp_a

74.1221542101633

In [7]:
y = exp_a / sum_exp_a

In [8]:
y

array([0.01821127, 0.24519181, 0.73659691])

In [16]:
def softmax(x):
    c = np.max(x) # 오버플로 방지
    exp_x = np.exp(x-c) # 오버플로 방지
    sum_exp_x = np.sum(exp_x)
    y = exp_x / sum_exp_x
    return y

### 소프트맥스 함수의 특징

In [17]:
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)

In [18]:
y

array([0.01821127, 0.24519181, 0.73659691])

In [19]:
np.sum(y)

1.0